// //----------------------
// // <auto-generated>
// //     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// // </auto-generated>
// //----------------------
//
// #pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
// #pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
// #pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
// #pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
// #pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
// #pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
// #pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
// #pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
//
// namespace Dashboard.API.Model
// {
//     using System = global::System;
//
//
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class ContestApplication
//     {
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("userId")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
//         [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
//         public System.Guid UserId { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("creationDate")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.DateTime CreationDate { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("justification")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Justification { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("status")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
//         [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
//         [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
//         public ContestApplicationStatus Status { get; set; }
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class Team
//     {
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("name")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
//         [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
//         public string Name { get; set; }
//
//         /// <summary>
//         /// поток, 1, 2, 3
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("section")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public int Section { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("contestCases")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<ContestCase> ContestCases { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("Managers")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<Manager> Managers { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("formOfParticipation")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
//         [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
//         [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
//         public FormOfParticipation FormOfParticipation { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("repositoryLink")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string RepositoryLink { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("additionalRepositoryLink")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string AdditionalRepositoryLink { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("presentationLink")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string PresentationLink { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("videoLink")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string VideoLink { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("openUniversityProjectLink")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string OpenUniversityProjectLink { get; set; }
//
//         /// <summary>
//         /// Дополнительные материалы, urls api и прочее
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("additionalInfo")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string AdditionalInfo { get; set; }
//
//         /// <summary>
//         /// Описание проекта текстом
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("teaser")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Teaser { get; set; }
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class Skill
//     {
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("skillName")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string SkillName { get; set; }
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class AcceptanceCriteria
//     {
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("criteria")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Criteria { get; set; }
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class ContestCase
//     {
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("description")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Description { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("company")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public Company Company { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("acceptanceCriteria")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<AcceptanceCriteria> AcceptanceCriteria { get; set; }
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class Company
//     {
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("name")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Name { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("description")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Description { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("experts")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<Expert> Experts { get; set; }
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class PersonBase
//     {
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("firstname")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
//         [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
//         public string Firstname { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("middlename")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Middlename { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("lastname")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
//         [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
//         public string Lastname { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("telegramAccount")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string TelegramAccount { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("phoneNumber")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string PhoneNumber { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("email")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
//         [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
//         public string Email { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("about")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string About { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("photoUrl")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
//         [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
//         public string PhotoUrl { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("blocked")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public bool Blocked { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("role")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
//         public TulahackRole Role { get; set; }
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class Manager : PersonBase
//     {
//
//         [System.Text.Json.Serialization.JsonPropertyName("team")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public Team Team { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("age")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public int Age { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("certificateNeeded")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public bool CertificateNeeded { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("ManagerNumber")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public int ManagerNumber { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("companyName")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string CompanyName { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("jobTitle")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string JobTitle { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("attendingFirstTime")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public bool AttendingFirstTime { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("applicationConfirmationStatus")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public bool ApplicationConfirmationStatus { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("applicationSubmissionDate")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.DateTime ApplicationSubmissionDate { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("region")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Region { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("city")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string City { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("university")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string University { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("universityDepartment")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string UniversityDepartment { get; set; }
//
//         /// <summary>
//         /// форма обучения: очнаяб заочная, вечерняя
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("universityAttendanceFormat")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string UniversityAttendanceFormat { get; set; }
//
//         /// <summary>
//         /// форма образования: бюджет, коммерция
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("scholarship")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Scholarship { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("applicationNumber")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid ApplicationNumber { get; set; }
//
//         /// <summary>
//         /// очное или онлайн участие
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("attendanceType")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string AttendanceType { get; set; }
//
//         /// <summary>
//         /// Школьник, студент, специалист
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("educationType")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string EducationType { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("githubUrl")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string GithubUrl { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("skills")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<Skill> Skills { get; set; }
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class Expert : PersonBase
//     {
//
//         [System.Text.Json.Serialization.JsonPropertyName("company")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public Company Company { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("workPosition")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string WorkPosition { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("confirmed")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public bool Confirmed { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("badge")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public bool Badge { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("photoUrl")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string PhotoUrl { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("additionalContactPerson")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string AdditionalContactPerson { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("skills")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<Skill> Skills { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("pickedTeams")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<Team> PickedTeams { get; set; }
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class Moderator : PersonBase
//     {
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class Superuser : PersonBase
//     {
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class StorageFile
//     {
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("filename")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Filename { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("filepath")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Filepath { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("owner")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Owner { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("creationDate")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.DateTime CreationDate { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("revision")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public int Revision { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("purpose")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
//         public FilePurposeType Purpose { get; set; }
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class Province
//     {
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public int Id { get; set; }
//
//         [System.Text.Json.Serialization.JsonPropertyName("name")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Name { get; set; }
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public enum TulahackRole
//     {
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Visitor")]
//         Visitor = 0,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Manager")]
//         Manager = 1,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Expert")]
//         Expert = 2,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Moderator")]
//         Moderator = 3,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Superuser")]
//         Superuser = 4,
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public enum ContestApplicationStatus
//     {
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Unknown")]
//         Unknown = 0,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Created")]
//         Created = 1,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Accepted")]
//         Accepted = 2,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Pending")]
//         Pending = 3,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Declined")]
//         Declined = 4,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"ChangesRequested")]
//         ChangesRequested = 5,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"ClarificationRequested")]
//         ClarificationRequested = 6,
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public enum FilePurposeType
//     {
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Unknown")]
//         Unknown = 0,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Default")]
//         Default = 1,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"SolutionApplication")]
//         SolutionApplication = 2,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"SolutionPresentation")]
//         SolutionPresentation = 3,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"SolutionVideo")]
//         SolutionVideo = 4,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"SolutionTeaser")]
//         SolutionTeaser = 5,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"SolutionExtras")]
//         SolutionExtras = 6,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"TaskPresentation")]
//         TaskPresentation = 7,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"TaskExtras")]
//         TaskExtras = 8,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"FinalLeaderboard")]
//         FinalLeaderboard = 9,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"FinalDiploma")]
//         FinalDiploma = 10,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"FinalTeamDiploma")]
//         FinalTeamDiploma = 11,
//
//     }
//
//     /// <summary>
//     /// Форма участия: In person or online, очно или онлайн
//     /// </summary>
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public enum FormOfParticipation
//     {
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Unknown")]
//         Unknown = 0,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"InPerson")]
//         InPerson = 1,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Online")]
//         Online = 2,
//
//     }
//
//
// }
//
// #pragma warning restore 1591
// #pragma warning restore 1573
// #pragma warning restore  472
// #pragma warning restore  114
// #pragma warning restore  108
// #pragma warning restore 3016
// #pragma warning restore 8603