// //----------------------
// // <auto-generated>
// //     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// // </auto-generated>
// //----------------------
//
// #pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
// #pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
// #pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
// #pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
// #pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
// #pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
// #pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
// #pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
//
// namespace Tulahack.Dtos
// {
//     using System = global::System;
//
//
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class DashboardDto : System.ComponentModel.INotifyPropertyChanged
//     {
//         private int _participatorsCount;
//         private int _expertsCount;
//         private int _companiesCount;
//         private int _casesCount;
//         private int _teamsCount;
//         private string _topicTitle;
//         private string _topic;
//         private string _topicThumbnailUrl;
//         private System.Guid _upcomingEventId;
//         private string _eventThumbnailUrl;
//         private ContestTimelineDto _timeline;
//
//         [System.Text.Json.Serialization.JsonPropertyName("participatorsCount")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public int ParticipatorsCount
//         {
//             get { return _participatorsCount; }
//
//             set
//             {
//                 if (_participatorsCount != value)
//                 {
//                     _participatorsCount = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("expertsCount")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public int ExpertsCount
//         {
//             get { return _expertsCount; }
//
//             set
//             {
//                 if (_expertsCount != value)
//                 {
//                     _expertsCount = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("companiesCount")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public int CompaniesCount
//         {
//             get { return _companiesCount; }
//
//             set
//             {
//                 if (_companiesCount != value)
//                 {
//                     _companiesCount = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("casesCount")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public int CasesCount
//         {
//             get { return _casesCount; }
//
//             set
//             {
//                 if (_casesCount != value)
//                 {
//                     _casesCount = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("teamsCount")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public int TeamsCount
//         {
//             get { return _teamsCount; }
//
//             set
//             {
//                 if (_teamsCount != value)
//                 {
//                     _teamsCount = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("topicTitle")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string TopicTitle
//         {
//             get { return _topicTitle; }
//
//             set
//             {
//                 if (_topicTitle != value)
//                 {
//                     _topicTitle = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("topic")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Topic
//         {
//             get { return _topic; }
//
//             set
//             {
//                 if (_topic != value)
//                 {
//                     _topic = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("topicThumbnailUrl")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string TopicThumbnailUrl
//         {
//             get { return _topicThumbnailUrl; }
//
//             set
//             {
//                 if (_topicThumbnailUrl != value)
//                 {
//                     _topicThumbnailUrl = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("upcomingEventId")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid UpcomingEventId
//         {
//             get { return _upcomingEventId; }
//
//             set
//             {
//                 if (_upcomingEventId != value)
//                 {
//                     _upcomingEventId = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("eventThumbnailUrl")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string EventThumbnailUrl
//         {
//             get { return _eventThumbnailUrl; }
//
//             set
//             {
//                 if (_eventThumbnailUrl != value)
//                 {
//                     _eventThumbnailUrl = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("timeline")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public ContestTimelineDto Timeline
//         {
//             get { return _timeline; }
//
//             set
//             {
//                 if (_timeline != value)
//                 {
//                     _timeline = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
//
//         protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
//         {
//             var handler = PropertyChanged;
//             if (handler != null)
//                 handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
//         }
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class ContestTimelineDto : System.ComponentModel.INotifyPropertyChanged
//     {
//         private System.Collections.Generic.IEnumerable<TimelineItemDto> _items;
//         private System.DateTime _hackathonStart;
//         private System.DateTime _hackathonEnd;
//         private System.DateTime _codingBeginning;
//         private System.DateTime _codingDeadline;
//
//         [System.Text.Json.Serialization.JsonPropertyName("items")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<TimelineItemDto> Items
//         {
//             get { return _items; }
//
//             set
//             {
//                 if (_items != value)
//                 {
//                     _items = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("hackathonStart")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.DateTime HackathonStart
//         {
//             get { return _hackathonStart; }
//
//             set
//             {
//                 if (_hackathonStart != value)
//                 {
//                     _hackathonStart = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("hackathonEnd")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.DateTime HackathonEnd
//         {
//             get { return _hackathonEnd; }
//
//             set
//             {
//                 if (_hackathonEnd != value)
//                 {
//                     _hackathonEnd = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("codingBeginning")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.DateTime CodingBeginning
//         {
//             get { return _codingBeginning; }
//
//             set
//             {
//                 if (_codingBeginning != value)
//                 {
//                     _codingBeginning = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("codingDeadline")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.DateTime CodingDeadline
//         {
//             get { return _codingDeadline; }
//
//             set
//             {
//                 if (_codingDeadline != value)
//                 {
//                     _codingDeadline = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
//
//         protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
//         {
//             var handler = PropertyChanged;
//             if (handler != null)
//                 handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
//         }
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class TimelineItemDto : System.ComponentModel.INotifyPropertyChanged
//     {
//         private TimelineItemTypeDto _itemType;
//         private System.DateTime _start;
//         private System.DateTime _end;
//         private string _label;
//         private System.DateTime? _deadline;
//         private string _url;
//         private string _message;
//         private string _extra;
//
//         [System.Text.Json.Serialization.JsonPropertyName("itemType")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//
//         public TimelineItemTypeDto ItemType
//         {
//             get { return _itemType; }
//
//             set
//             {
//                 if (_itemType != value)
//                 {
//                     _itemType = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("start")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.DateTime Start
//         {
//             get { return _start; }
//
//             set
//             {
//                 if (_start != value)
//                 {
//                     _start = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("end")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.DateTime End
//         {
//             get { return _end; }
//
//             set
//             {
//                 if (_end != value)
//                 {
//                     _end = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("label")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Label
//         {
//             get { return _label; }
//
//             set
//             {
//                 if (_label != value)
//                 {
//                     _label = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("deadline")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.DateTime? Deadline
//         {
//             get { return _deadline; }
//
//             set
//             {
//                 if (_deadline != value)
//                 {
//                     _deadline = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("url")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Url
//         {
//             get { return _url; }
//
//             set
//             {
//                 if (_url != value)
//                 {
//                     _url = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("message")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Message
//         {
//             get { return _message; }
//
//             set
//             {
//                 if (_message != value)
//                 {
//                     _message = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("extra")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Extra
//         {
//             get { return _extra; }
//
//             set
//             {
//                 if (_extra != value)
//                 {
//                     _extra = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
//
//         protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
//         {
//             var handler = PropertyChanged;
//             if (handler != null)
//                 handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
//         }
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class TeamDto : System.ComponentModel.INotifyPropertyChanged
//     {
//         private System.Guid _id;
//         private string _name;
//         private int _section;
//         private System.Collections.Generic.IEnumerable<ContestCaseDto> _contestCases;
//         private System.Collections.Generic.IEnumerable<ManagerDto> _Managers;
//         private int _teamSize;
//         private string _repositoryLink;
//         private FormOfParticipationTypeDto _formOfParticipation;
//         private string _additionalRepositoryLink;
//         private string _presentationLink;
//         private string _videoLink;
//         private string _openUniversityProjectLink;
//         private string _additionalInfo;
//         private string _teaser;
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id
//         {
//             get { return _id; }
//
//             set
//             {
//                 if (_id != value)
//                 {
//                     _id = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("name")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
//         [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
//         public string Name
//         {
//             get { return _name; }
//
//             set
//             {
//                 if (_name != value)
//                 {
//                     _name = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         /// <summary>
//         /// поток, 1, 2, 3
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("section")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public int Section
//         {
//             get { return _section; }
//
//             set
//             {
//                 if (_section != value)
//                 {
//                     _section = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("contestCases")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<ContestCaseDto> ContestCases
//         {
//             get { return _contestCases; }
//
//             set
//             {
//                 if (_contestCases != value)
//                 {
//                     _contestCases = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("Managers")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<ManagerDto> Managers
//         {
//             get { return _Managers; }
//
//             set
//             {
//                 if (_Managers != value)
//                 {
//                     _Managers = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("teamSize")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public int TeamSize
//         {
//             get { return _teamSize; }
//
//             set
//             {
//                 if (_teamSize != value)
//                 {
//                     _teamSize = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("repositoryLink")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
//         [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
//         public string RepositoryLink
//         {
//             get { return _repositoryLink; }
//
//             set
//             {
//                 if (_repositoryLink != value)
//                 {
//                     _repositoryLink = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("formOfParticipation")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//
//         public FormOfParticipationTypeDto FormOfParticipation
//         {
//             get { return _formOfParticipation; }
//
//             set
//             {
//                 if (_formOfParticipation != value)
//                 {
//                     _formOfParticipation = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("additionalRepositoryLink")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string AdditionalRepositoryLink
//         {
//             get { return _additionalRepositoryLink; }
//
//             set
//             {
//                 if (_additionalRepositoryLink != value)
//                 {
//                     _additionalRepositoryLink = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("presentationLink")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string PresentationLink
//         {
//             get { return _presentationLink; }
//
//             set
//             {
//                 if (_presentationLink != value)
//                 {
//                     _presentationLink = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("videoLink")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
//         [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
//         public string VideoLink
//         {
//             get { return _videoLink; }
//
//             set
//             {
//                 if (_videoLink != value)
//                 {
//                     _videoLink = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("openUniversityProjectLink")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
//         [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
//         public string OpenUniversityProjectLink
//         {
//             get { return _openUniversityProjectLink; }
//
//             set
//             {
//                 if (_openUniversityProjectLink != value)
//                 {
//                     _openUniversityProjectLink = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         /// <summary>
//         /// Дополнительные материалы, urls api и прочее
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("additionalInfo")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string AdditionalInfo
//         {
//             get { return _additionalInfo; }
//
//             set
//             {
//                 if (_additionalInfo != value)
//                 {
//                     _additionalInfo = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         /// <summary>
//         /// Описание проекта текстом
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("teaser")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Teaser
//         {
//             get { return _teaser; }
//
//             set
//             {
//                 if (_teaser != value)
//                 {
//                     _teaser = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
//
//         protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
//         {
//             var handler = PropertyChanged;
//             if (handler != null)
//                 handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
//         }
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class SkillDto : System.ComponentModel.INotifyPropertyChanged
//     {
//         private System.Guid _id;
//         private string _skillName;
//         private string _color;
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id
//         {
//             get { return _id; }
//
//             set
//             {
//                 if (_id != value)
//                 {
//                     _id = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("skillName")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string SkillName
//         {
//             get { return _skillName; }
//
//             set
//             {
//                 if (_skillName != value)
//                 {
//                     _skillName = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("color")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Color
//         {
//             get { return _color; }
//
//             set
//             {
//                 if (_color != value)
//                 {
//                     _color = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
//
//         protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
//         {
//             var handler = PropertyChanged;
//             if (handler != null)
//                 handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
//         }
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class AcceptanceCriteriaDto : System.ComponentModel.INotifyPropertyChanged
//     {
//         private System.Guid _id;
//         private string _criteria;
//         private string _color;
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id
//         {
//             get { return _id; }
//
//             set
//             {
//                 if (_id != value)
//                 {
//                     _id = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("criteria")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Criteria
//         {
//             get { return _criteria; }
//
//             set
//             {
//                 if (_criteria != value)
//                 {
//                     _criteria = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("color")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Color
//         {
//             get { return _color; }
//
//             set
//             {
//                 if (_color != value)
//                 {
//                     _color = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
//
//         protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
//         {
//             var handler = PropertyChanged;
//             if (handler != null)
//                 handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
//         }
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class ContestCaseDto : System.ComponentModel.INotifyPropertyChanged
//     {
//         private System.Guid _id;
//         private int _number;
//         private string _title;
//         private string _description;
//         private ContestCaseComplexityDto _complexity;
//         private System.Collections.Generic.IEnumerable<SkillDto> _techStack;
//         private CompanyDto _company;
//         private System.Collections.Generic.IEnumerable<AcceptanceCriteriaDto> _acceptanceCriteria;
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id
//         {
//             get { return _id; }
//
//             set
//             {
//                 if (_id != value)
//                 {
//                     _id = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("number")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public int Number
//         {
//             get { return _number; }
//
//             set
//             {
//                 if (_number != value)
//                 {
//                     _number = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("title")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Title
//         {
//             get { return _title; }
//
//             set
//             {
//                 if (_title != value)
//                 {
//                     _title = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("description")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Description
//         {
//             get { return _description; }
//
//             set
//             {
//                 if (_description != value)
//                 {
//                     _description = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("complexity")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//
//         public ContestCaseComplexityDto Complexity
//         {
//             get { return _complexity; }
//
//             set
//             {
//                 if (_complexity != value)
//                 {
//                     _complexity = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("techStack")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<SkillDto> TechStack
//         {
//             get { return _techStack; }
//
//             set
//             {
//                 if (_techStack != value)
//                 {
//                     _techStack = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("company")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public CompanyDto Company
//         {
//             get { return _company; }
//
//             set
//             {
//                 if (_company != value)
//                 {
//                     _company = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("acceptanceCriteria")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<AcceptanceCriteriaDto> AcceptanceCriteria
//         {
//             get { return _acceptanceCriteria; }
//
//             set
//             {
//                 if (_acceptanceCriteria != value)
//                 {
//                     _acceptanceCriteria = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
//
//         protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
//         {
//             var handler = PropertyChanged;
//             if (handler != null)
//                 handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
//         }
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class CompanyDto : System.ComponentModel.INotifyPropertyChanged
//     {
//         private System.Guid _id;
//         private string _name;
//         private string _description;
//         private System.Collections.Generic.IEnumerable<ExpertDto> _experts;
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id
//         {
//             get { return _id; }
//
//             set
//             {
//                 if (_id != value)
//                 {
//                     _id = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("name")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Name
//         {
//             get { return _name; }
//
//             set
//             {
//                 if (_name != value)
//                 {
//                     _name = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("description")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Description
//         {
//             get { return _description; }
//
//             set
//             {
//                 if (_description != value)
//                 {
//                     _description = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("experts")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<ExpertDto> Experts
//         {
//             get { return _experts; }
//
//             set
//             {
//                 if (_experts != value)
//                 {
//                     _experts = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
//
//         protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
//         {
//             var handler = PropertyChanged;
//             if (handler != null)
//                 handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
//         }
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class PersonBaseDto : System.ComponentModel.INotifyPropertyChanged
//     {
//         private System.Guid _id;
//         private string _firstname;
//         private string _middlename;
//         private string _lastname;
//         private string _telegramAccount;
//         private string _phoneNumber;
//         private string _email;
//         private string _about;
//         private string _photoUrl;
//         private bool _blocked;
//         private TulahackRoleDto _role;
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id
//         {
//             get { return _id; }
//
//             set
//             {
//                 if (_id != value)
//                 {
//                     _id = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("firstname")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Firstname
//         {
//             get { return _firstname; }
//
//             set
//             {
//                 if (_firstname != value)
//                 {
//                     _firstname = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("middlename")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Middlename
//         {
//             get { return _middlename; }
//
//             set
//             {
//                 if (_middlename != value)
//                 {
//                     _middlename = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("lastname")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Lastname
//         {
//             get { return _lastname; }
//
//             set
//             {
//                 if (_lastname != value)
//                 {
//                     _lastname = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("telegramAccount")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string TelegramAccount
//         {
//             get { return _telegramAccount; }
//
//             set
//             {
//                 if (_telegramAccount != value)
//                 {
//                     _telegramAccount = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("phoneNumber")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string PhoneNumber
//         {
//             get { return _phoneNumber; }
//
//             set
//             {
//                 if (_phoneNumber != value)
//                 {
//                     _phoneNumber = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("email")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Email
//         {
//             get { return _email; }
//
//             set
//             {
//                 if (_email != value)
//                 {
//                     _email = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("about")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string About
//         {
//             get { return _about; }
//
//             set
//             {
//                 if (_about != value)
//                 {
//                     _about = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("photoUrl")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
//         [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
//         public string PhotoUrl
//         {
//             get { return _photoUrl; }
//
//             set
//             {
//                 if (_photoUrl != value)
//                 {
//                     _photoUrl = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("blocked")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public bool Blocked
//         {
//             get { return _blocked; }
//
//             set
//             {
//                 if (_blocked != value)
//                 {
//                     _blocked = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("role")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//
//         public TulahackRoleDto Role
//         {
//             get { return _role; }
//
//             set
//             {
//                 if (_role != value)
//                 {
//                     _role = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
//
//         protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
//         {
//             var handler = PropertyChanged;
//             if (handler != null)
//                 handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
//         }
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class ManagerDto : PersonBaseDto
//     {
//         private TeamDto _team;
//         private int _age;
//         private bool _certificateNeeded;
//         private int _ManagerNumber;
//         private string _companyName;
//         private string _jobTitle;
//         private bool _attendingFirstTime;
//         private bool _applicationConfirmationStatus;
//         private System.DateTime _applicationSubmissionDate;
//         private string _region;
//         private string _city;
//         private string _university;
//         private string _universityDepartment;
//         private string _universityAttendanceFormat;
//         private string _scholarship;
//         private System.Guid _applicationNumber;
//         private string _attendanceType;
//         private string _educationType;
//         private System.Collections.Generic.IEnumerable<SkillDto> _skills;
//
//         [System.Text.Json.Serialization.JsonPropertyName("team")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public TeamDto Team
//         {
//             get { return _team; }
//
//             set
//             {
//                 if (_team != value)
//                 {
//                     _team = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("age")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public int Age
//         {
//             get { return _age; }
//
//             set
//             {
//                 if (_age != value)
//                 {
//                     _age = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("certificateNeeded")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public bool CertificateNeeded
//         {
//             get { return _certificateNeeded; }
//
//             set
//             {
//                 if (_certificateNeeded != value)
//                 {
//                     _certificateNeeded = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("ManagerNumber")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public int ManagerNumber
//         {
//             get { return _ManagerNumber; }
//
//             set
//             {
//                 if (_ManagerNumber != value)
//                 {
//                     _ManagerNumber = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("companyName")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string CompanyName
//         {
//             get { return _companyName; }
//
//             set
//             {
//                 if (_companyName != value)
//                 {
//                     _companyName = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("jobTitle")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string JobTitle
//         {
//             get { return _jobTitle; }
//
//             set
//             {
//                 if (_jobTitle != value)
//                 {
//                     _jobTitle = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("attendingFirstTime")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public bool AttendingFirstTime
//         {
//             get { return _attendingFirstTime; }
//
//             set
//             {
//                 if (_attendingFirstTime != value)
//                 {
//                     _attendingFirstTime = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("applicationConfirmationStatus")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public bool ApplicationConfirmationStatus
//         {
//             get { return _applicationConfirmationStatus; }
//
//             set
//             {
//                 if (_applicationConfirmationStatus != value)
//                 {
//                     _applicationConfirmationStatus = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("applicationSubmissionDate")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.DateTime ApplicationSubmissionDate
//         {
//             get { return _applicationSubmissionDate; }
//
//             set
//             {
//                 if (_applicationSubmissionDate != value)
//                 {
//                     _applicationSubmissionDate = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("region")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Region
//         {
//             get { return _region; }
//
//             set
//             {
//                 if (_region != value)
//                 {
//                     _region = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("city")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string City
//         {
//             get { return _city; }
//
//             set
//             {
//                 if (_city != value)
//                 {
//                     _city = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("university")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string University
//         {
//             get { return _university; }
//
//             set
//             {
//                 if (_university != value)
//                 {
//                     _university = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("universityDepartment")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string UniversityDepartment
//         {
//             get { return _universityDepartment; }
//
//             set
//             {
//                 if (_universityDepartment != value)
//                 {
//                     _universityDepartment = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         /// <summary>
//         /// форма обучения: очнаяб заочная, вечерняя
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("universityAttendanceFormat")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string UniversityAttendanceFormat
//         {
//             get { return _universityAttendanceFormat; }
//
//             set
//             {
//                 if (_universityAttendanceFormat != value)
//                 {
//                     _universityAttendanceFormat = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         /// <summary>
//         /// форма образования: бюджет, коммерция
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("scholarship")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Scholarship
//         {
//             get { return _scholarship; }
//
//             set
//             {
//                 if (_scholarship != value)
//                 {
//                     _scholarship = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("applicationNumber")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid ApplicationNumber
//         {
//             get { return _applicationNumber; }
//
//             set
//             {
//                 if (_applicationNumber != value)
//                 {
//                     _applicationNumber = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         /// <summary>
//         /// очное или онлайн участие
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("attendanceType")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string AttendanceType
//         {
//             get { return _attendanceType; }
//
//             set
//             {
//                 if (_attendanceType != value)
//                 {
//                     _attendanceType = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         /// <summary>
//         /// Школьник, студент, специалист
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("educationType")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string EducationType
//         {
//             get { return _educationType; }
//
//             set
//             {
//                 if (_educationType != value)
//                 {
//                     _educationType = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("skills")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<SkillDto> Skills
//         {
//             get { return _skills; }
//
//             set
//             {
//                 if (_skills != value)
//                 {
//                     _skills = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class ExpertDto : PersonBaseDto
//     {
//         private CompanyDto _company;
//         private string _workPosition;
//         private bool _confirmed;
//         private bool _badge;
//         private string _photoUrl;
//         private string _additionalContactPerson;
//         private System.Collections.Generic.IEnumerable<SkillDto> _skills;
//         private System.Collections.Generic.IEnumerable<TeamDto> _pickedTeams;
//
//         [System.Text.Json.Serialization.JsonPropertyName("company")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public CompanyDto Company
//         {
//             get { return _company; }
//
//             set
//             {
//                 if (_company != value)
//                 {
//                     _company = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("workPosition")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string WorkPosition
//         {
//             get { return _workPosition; }
//
//             set
//             {
//                 if (_workPosition != value)
//                 {
//                     _workPosition = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("confirmed")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public bool Confirmed
//         {
//             get { return _confirmed; }
//
//             set
//             {
//                 if (_confirmed != value)
//                 {
//                     _confirmed = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("badge")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public bool Badge
//         {
//             get { return _badge; }
//
//             set
//             {
//                 if (_badge != value)
//                 {
//                     _badge = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("photoUrl")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string PhotoUrl
//         {
//             get { return _photoUrl; }
//
//             set
//             {
//                 if (_photoUrl != value)
//                 {
//                     _photoUrl = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("additionalContactPerson")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string AdditionalContactPerson
//         {
//             get { return _additionalContactPerson; }
//
//             set
//             {
//                 if (_additionalContactPerson != value)
//                 {
//                     _additionalContactPerson = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("skills")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<SkillDto> Skills
//         {
//             get { return _skills; }
//
//             set
//             {
//                 if (_skills != value)
//                 {
//                     _skills = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("pickedTeams")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<TeamDto> PickedTeams
//         {
//             get { return _pickedTeams; }
//
//             set
//             {
//                 if (_pickedTeams != value)
//                 {
//                     _pickedTeams = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class ModeratorDto : PersonBaseDto
//     {
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class ProvinceDto : System.ComponentModel.INotifyPropertyChanged
//     {
//         private int _id;
//         private string _name;
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public int Id
//         {
//             get { return _id; }
//
//             set
//             {
//                 if (_id != value)
//                 {
//                     _id = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("name")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Name
//         {
//             get { return _name; }
//
//             set
//             {
//                 if (_name != value)
//                 {
//                     _name = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
//
//         protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
//         {
//             var handler = PropertyChanged;
//             if (handler != null)
//                 handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
//         }
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class StorageFileDto : System.ComponentModel.INotifyPropertyChanged
//     {
//         private System.Guid _id;
//         private string _filename;
//         private string _filepath;
//         private System.Guid _owner;
//         private System.DateTime _creationDate;
//         private int _revision;
//         private StorageFilePurposeTypeDto _purpose;
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id
//         {
//             get { return _id; }
//
//             set
//             {
//                 if (_id != value)
//                 {
//                     _id = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("filename")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Filename
//         {
//             get { return _filename; }
//
//             set
//             {
//                 if (_filename != value)
//                 {
//                     _filename = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("filepath")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Filepath
//         {
//             get { return _filepath; }
//
//             set
//             {
//                 if (_filepath != value)
//                 {
//                     _filepath = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("owner")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Owner
//         {
//             get { return _owner; }
//
//             set
//             {
//                 if (_owner != value)
//                 {
//                     _owner = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("creationDate")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.DateTime CreationDate
//         {
//             get { return _creationDate; }
//
//             set
//             {
//                 if (_creationDate != value)
//                 {
//                     _creationDate = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("revision")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public int Revision
//         {
//             get { return _revision; }
//
//             set
//             {
//                 if (_revision != value)
//                 {
//                     _revision = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("purpose")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//
//         public StorageFilePurposeTypeDto Purpose
//         {
//             get { return _purpose; }
//
//             set
//             {
//                 if (_purpose != value)
//                 {
//                     _purpose = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
//
//         protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
//         {
//             var handler = PropertyChanged;
//             if (handler != null)
//                 handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
//         }
//     }
//
//     /// <summary>
//     /// Уведомление в верхней части приложения
//     /// </summary>
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class InAppNotification : System.ComponentModel.INotifyPropertyChanged
//     {
//         private System.Guid _id;
//         private string _icon = "CursorHoverRegular";
//         private string _title;
//         private System.DateTime _creationDate;
//         private string _message;
//         private string _extra;
//         private EventTypeDto _type;
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id
//         {
//             get { return _id; }
//
//             set
//             {
//                 if (_id != value)
//                 {
//                     _id = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         /// <summary>
//         /// Ключ иконки, по этому ключу выставляется картинка в левой части уведомления
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("icon")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Icon
//         {
//             get { return _icon; }
//
//             set
//             {
//                 if (_icon != value)
//                 {
//                     _icon = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         /// <summary>
//         /// Заголовок уведомления
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("title")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
//         [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
//         public string Title
//         {
//             get { return _title; }
//
//             set
//             {
//                 if (_title != value)
//                 {
//                     _title = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         /// <summary>
//         /// Дата создания уведомления, устанавливается на бекенде
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("creationDate")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
//         [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
//         public System.DateTime CreationDate
//         {
//             get { return _creationDate; }
//
//             set
//             {
//                 if (_creationDate != value)
//                 {
//                     _creationDate = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         /// <summary>
//         /// Текст уведомления
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("message")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
//         [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
//         public string Message
//         {
//             get { return _message; }
//
//             set
//             {
//                 if (_message != value)
//                 {
//                     _message = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         /// <summary>
//         /// Дополнительная информация, текст второго блока уведомления
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("extra")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Extra
//         {
//             get { return _extra; }
//
//             set
//             {
//                 if (_extra != value)
//                 {
//                     _extra = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         /// <summary>
//         /// Тип события, которое произошло и создало уведомление. Это может быть как автоматическая рассылка, так и событие в системе
//         /// </summary>
//
//         [System.Text.Json.Serialization.JsonPropertyName("type")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
//         [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
//
//         public EventTypeDto Type
//         {
//             get { return _type; }
//
//             set
//             {
//                 if (_type != value)
//                 {
//                     _type = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
//
//         protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
//         {
//             var handler = PropertyChanged;
//             if (handler != null)
//                 handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
//         }
//     }
//
//     /// <summary>
//     /// Пользовательские настройки: настройки клиента, темы приложения, уведомлений и прочее
//     /// </summary>
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class UserPreferencesDto : System.ComponentModel.INotifyPropertyChanged
//     {
//         private System.Guid _id;
//         private UserPreferredThemeDto _selectedTheme;
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id
//         {
//             get { return _id; }
//
//             set
//             {
//                 if (_id != value)
//                 {
//                     _id = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("selectedTheme")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//
//         public UserPreferredThemeDto SelectedTheme
//         {
//             get { return _selectedTheme; }
//
//             set
//             {
//                 if (_selectedTheme != value)
//                 {
//                     _selectedTheme = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
//
//         protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
//         {
//             var handler = PropertyChanged;
//             if (handler != null)
//                 handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
//         }
//     }
//
//     /// <summary>
//     /// Событие хакатона: чекпоинты, дедлайны, выступления и мероприятия хакатона
//     /// </summary>
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class HackathonEventDto : System.ComponentModel.INotifyPropertyChanged
//     {
//         private System.Guid _id;
//         private string _eventTitle;
//         private string _content;
//         private string _eventThumbnailUrl;
//         private TimelineItemDto _timelineItem;
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id
//         {
//             get { return _id; }
//
//             set
//             {
//                 if (_id != value)
//                 {
//                     _id = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("eventTitle")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string EventTitle
//         {
//             get { return _eventTitle; }
//
//             set
//             {
//                 if (_eventTitle != value)
//                 {
//                     _eventTitle = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("content")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string Content
//         {
//             get { return _content; }
//
//             set
//             {
//                 if (_content != value)
//                 {
//                     _content = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("eventThumbnailUrl")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public string EventThumbnailUrl
//         {
//             get { return _eventThumbnailUrl; }
//
//             set
//             {
//                 if (_eventThumbnailUrl != value)
//                 {
//                     _eventThumbnailUrl = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("timelineItem")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public TimelineItemDto TimelineItem
//         {
//             get { return _timelineItem; }
//
//             set
//             {
//                 if (_timelineItem != value)
//                 {
//                     _timelineItem = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
//
//         protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
//         {
//             var handler = PropertyChanged;
//             if (handler != null)
//                 handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
//         }
//     }
//
//     /// <summary>
//     /// Настройки хакатона
//     /// </summary>
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public partial class HackathonSettingsDto : System.ComponentModel.INotifyPropertyChanged
//     {
//         private System.Guid _id;
//         private System.Guid _currentTopicId;
//         private ContestTimelineDto _timeline;
//         private HackathonEventDto _events;
//         private System.Collections.Generic.IEnumerable<ModeratorDto> _moderators;
//         private System.Collections.Generic.IEnumerable<CompanyDto> _companies;
//         private System.Collections.Generic.IEnumerable<ContestCaseDto> _cases;
//
//         [System.Text.Json.Serialization.JsonPropertyName("id")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid Id
//         {
//             get { return _id; }
//
//             set
//             {
//                 if (_id != value)
//                 {
//                     _id = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("currentTopicId")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Guid CurrentTopicId
//         {
//             get { return _currentTopicId; }
//
//             set
//             {
//                 if (_currentTopicId != value)
//                 {
//                     _currentTopicId = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("timeline")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public ContestTimelineDto Timeline
//         {
//             get { return _timeline; }
//
//             set
//             {
//                 if (_timeline != value)
//                 {
//                     _timeline = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("events")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public HackathonEventDto Events
//         {
//             get { return _events; }
//
//             set
//             {
//                 if (_events != value)
//                 {
//                     _events = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("moderators")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<ModeratorDto> Moderators
//         {
//             get { return _moderators; }
//
//             set
//             {
//                 if (_moderators != value)
//                 {
//                     _moderators = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("companies")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<CompanyDto> Companies
//         {
//             get { return _companies; }
//
//             set
//             {
//                 if (_companies != value)
//                 {
//                     _companies = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         [System.Text.Json.Serialization.JsonPropertyName("cases")]
//
//         [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
//         public System.Collections.Generic.IEnumerable<ContestCaseDto> Cases
//         {
//             get { return _cases; }
//
//             set
//             {
//                 if (_cases != value)
//                 {
//                     _cases = value;
//                     RaisePropertyChanged();
//                 }
//             }
//         }
//
//         public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
//
//         protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
//         {
//             var handler = PropertyChanged;
//             if (handler != null)
//                 handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
//         }
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public enum TulahackRoleDto
//     {
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Visitor")]
//         Visitor = 0,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Manager")]
//         Manager = 1,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Expert")]
//         Expert = 2,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Moderator")]
//         Moderator = 3,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Superuser")]
//         Superuser = 4,
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public enum UserPreferredThemeDto
//     {
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Default")]
//         Default = 0,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Light")]
//         Light = 1,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Dark")]
//         Dark = 2,
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public enum EventTypeDto
//     {
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Unknown")]
//         Unknown = 0,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Todo")]
//         Todo = 1,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Urgent")]
//         Urgent = 2,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Doing")]
//         Doing = 3,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Processing")]
//         Processing = 4,
//
//     }
//
//     /// <summary>
//     /// In person or online, очно или онлайн
//     /// </summary>
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public enum FormOfParticipationTypeDto
//     {
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Unknown")]
//         Unknown = 0,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"InPerson")]
//         InPerson = 1,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Online")]
//         Online = 2,
//
//     }
//
//     /// <summary>
//     /// Timeline point type: checkpoint, hackathon offline meetup, deadline, online event or whatever else
//     /// </summary>
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public enum TimelineItemTypeDto
//     {
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Unknown")]
//         Unknown = 0,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Checkpoint")]
//         Checkpoint = 1,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Deadline")]
//         Deadline = 2,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Event")]
//         Event = 3,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Meetup")]
//         Meetup = 4,
//
//     }
//
//     /// <summary>
//     /// Contest case complexity, describes how hard it is to complete the task
//     /// </summary>
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public enum ContestCaseComplexityDto
//     {
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Unknown")]
//         Unknown = 0,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Beginner")]
//         Beginner = 1,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Easy")]
//         Easy = 2,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Normal")]
//         Normal = 3,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Hard")]
//         Hard = 4,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Insane")]
//         Insane = 5,
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public enum StorageFilePurposeTypeDto
//     {
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Unknown")]
//         Unknown = 0,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Default")]
//         Default = 1,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"SolutionApplication")]
//         SolutionApplication = 2,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"SolutionPresentation")]
//         SolutionPresentation = 3,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"SolutionVideo")]
//         SolutionVideo = 4,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"SolutionTeaser")]
//         SolutionTeaser = 5,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"SolutionExtras")]
//         SolutionExtras = 6,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"TaskPresentation")]
//         TaskPresentation = 7,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"TaskExtras")]
//         TaskExtras = 8,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"FinalLeaderboard")]
//         FinalLeaderboard = 9,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"FinalDiploma")]
//         FinalDiploma = 10,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"FinalTeamDiploma")]
//         FinalTeamDiploma = 11,
//
//     }
//
//     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
//     public enum ApprovalStatusDto
//     {
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Unknown")]
//         Unknown = 0,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Created")]
//         Created = 1,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Accepted")]
//         Accepted = 2,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Pending")]
//         Pending = 3,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"Declined")]
//         Declined = 4,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"ChangesRequested")]
//         ChangesRequested = 5,
//
//         [System.Runtime.Serialization.EnumMember(Value = @"ClarificationRequested")]
//         ClarificationRequested = 6,
//
//     }
//
//
// }
//
// #pragma warning restore 1591
// #pragma warning restore 1573
// #pragma warning restore  472
// #pragma warning restore  114
// #pragma warning restore  108
// #pragma warning restore 3016
// #pragma warning restore 8603