"""Models

Revision ID: 242328cec209
Revises: 69c237479d84
Create Date: 2025-04-19 16:27:17.441970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242328cec209'
down_revision: Union[str, None] = '69c237479d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects_configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_token', sa.String(), nullable=False),
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('project', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_token'),
    sa.UniqueConstraint('project_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects_configurations')
    op.drop_table('projects')
    # ### end Alembic commands ###
